apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-order
  name: eshop-order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-order
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-order
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SERVICE
                  name: eshop-order-env
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER
                  name: eshop-order-env
            - name: POSTGRESQL_COMMAND_CONN_ATTEMPS
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_COMMAND_CONN_ATTEMPS
                  name: eshop-order-env
            - name: POSTGRESQL_COMMAND_CONN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_COMMAND_CONN_TIMEOUT
                  name: eshop-order-env
            - name: POSTGRESQL_COMMAND_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_COMMAND_MAX_POOL_SIZE
                  name: eshop-order-env
            - name: POSTGRESQL_COMMAND_URL
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_COMMAND_URL
                  name: eshop-order-env
            - name: POSTGRESQL_QUERY_CONN_ATTEMPS
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_QUERY_CONN_ATTEMPS
                  name: eshop-order-env
            - name: POSTGRESQL_QUERY_CONN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_QUERY_CONN_TIMEOUT
                  name: eshop-order-env
            - name: POSTGRESQL_QUERY_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_QUERY_MAX_POOL_SIZE
                  name: eshop-order-env
            - name: POSTGRESQL_QUERY_URL
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_QUERY_URL
                  name: eshop-order-env
            - name: PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: PRODUCT_SERVICE
                  name: eshop-order-env
            - name: SHIPPING_COST_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: SHIPPING_COST_SERVICE
                  name: eshop-order-env
            - name: WAREHOUSE_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: WAREHOUSE_SERVICE
                  name: eshop-order-env
          image: gcr.io/eshop-444706/eshop-order:latest
          name: eshop-order
          ports:
            - containerPort: 2004
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "536870912"
            requests:
              cpu: 500m
              memory: "268435456"
      restartPolicy: Always
