apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-auth
  name: eshop-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-auth
    spec:
      containers:
        - env:
            - name: AWS_COGNITO_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_COGNITO_APP_ID
                  name: eshop-auth-env
            - name: AWS_COGNITO_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_COGNITO_REGION
                  name: eshop-auth-env
          image: gcr.io/eshop-444706/eshop-auth:latest
          name: eshop-auth
          ports:
            - containerPort: 2003
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "536870912"
            requests:
              cpu: 500m
              memory: "268435456"
      restartPolicy: Always
