apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-fe-customer
  name: eshop-fe-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-fe-customer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-fe-customer
    spec:
      containers:
        - env:
            - name: CART_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: CART_SERVICE
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_CART_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CART_SERVICE
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_COGNITO_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_COGNITO_CLIENT_ID
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_COGNITO_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_COGNITO_DOMAIN
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_IN
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_COGNITO_REDIRECT_SIGN_OUT
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_COGNITO_USER_POOL_ID
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_COGNITO_USER_POOL_ID
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_IMAGE_CLOUDFRONT
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_IMAGE_CLOUDFRONT
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_ORDER_SERVICE
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_PAYMENT_SERVICE
                  name: eshop-fe-customer-env
            - name: NEXT_PUBLIC_PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_PRODUCT_SERVICE
                  name: eshop-fe-customer-env
            - name: ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE
                  name: eshop-fe-customer-env
            - name: PAYMENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: PAYMENT_SERVICE
                  name: eshop-fe-customer-env
            - name: PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: PRODUCT_SERVICE
                  name: eshop-fe-customer-env
          image: gcr.io/eshop-444706/eshop-fe-customer:latest
          name: eshop-fe-customer
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "2147483648"
            requests:
              cpu: 583m
              memory: "1073741824"
      restartPolicy: Always
