apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-warehouse
  name: eshop-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-warehouse
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-warehouse
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SERVICE
                  name: eshop-warehouse-env
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER
                  name: eshop-warehouse-env
            - name: POSTGRESQL_CONN_ATTEMPS
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_CONN_ATTEMPS
                  name: eshop-warehouse-env
            - name: POSTGRESQL_CONN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_CONN_TIMEOUT
                  name: eshop-warehouse-env
            - name: POSTGRESQL_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_MAX_POOL_SIZE
                  name: eshop-warehouse-env
            - name: POSTGRESQL_URL
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_URL
                  name: eshop-warehouse-env
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: eshop-warehouse-env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: eshop-warehouse-env
          image: gcr.io/eshop-444706/eshop-warehouse:latest
          name: eshop-warehouse
          ports:
            - containerPort: 2005
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "536870912"
            requests:
              cpu: 500m
              memory: "268435456"
      restartPolicy: Always
