apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-sales-report
  name: eshop-sales-report
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-sales-report
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-sales-report
    spec:
      containers:
        - env:
            - name: API_V1_STR
              valueFrom:
                configMapKeyRef:
                  key: API_V1_STR
                  name: eshop-sales-report-env
            - name: BACKEND_CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: BACKEND_CORS_ORIGINS
                  name: eshop-sales-report-env
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: eshop-sales-report-env
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVER
                  name: eshop-sales-report-env
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CONSUMER_GROUP
                  name: eshop-sales-report-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: eshop-sales-report-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: eshop-sales-report-env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: eshop-sales-report-env
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_SERVER
                  name: eshop-sales-report-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: eshop-sales-report-env
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: PROJECT_NAME
                  name: eshop-sales-report-env
          image: gcr.io/eshop-444706/eshop-sales-report:latest
          name: eshop-sales-report
          ports:
            - containerPort: 2007
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: "268435456"
            requests:
              cpu: "1"
              memory: "134217728"
      restartPolicy: Always
