apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-auth
  name: eshop-auth
spec:
  ports:
    - name: "2003"
      port: 2003
      targetPort: 2003
  selector:
    io.kompose.service: eshop-auth
