apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: eshop-cart
  name: eshop-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-cart
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: eshop-cart
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SERVICE
                  name: eshop-cart-env
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER
                  name: eshop-cart-env
            - name: MYSQL_CONN_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_CONN_MAX_LIFETIME
                  name: eshop-cart-env
            - name: MYSQL_MAX_IDLE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_MAX_IDLE_CONNECTION
                  name: eshop-cart-env
            - name: MYSQL_MAX_OPEN_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_MAX_OPEN_CONNECTION
                  name: eshop-cart-env
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_URL
                  name: eshop-cart-env
            - name: ORDER_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: ORDER_SERVICE
                  name: eshop-cart-env
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: eshop-cart-env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: eshop-cart-env
          image: gcr.io/eshop-444706/eshop-eshop-cart:latest
          name: eshop-cart
          ports:
            - containerPort: 2002
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: eshop-cart-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: eshop-cart-cm0
          name: eshop-cart-cm0
