apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql-order-read
  name: postgresql-order-read
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-order-read
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgresql-order-read
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: orders_read
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: gcr.io/eshop-444706/postgresql-order-read:v1
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
            failureThreshold: 10
            timeoutSeconds: 20
          name: postgresql-order-read
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-order-read-data
      restartPolicy: Always
      volumes:
        - name: postgres-order-read-data
          persistentVolumeClaim:
            claimName: postgres-order-read-data
