apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql-order-read
  name: postgresql-order-read
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5432
  selector:
    io.kompose.service: postgresql-order-read
