apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql-sales
  name: postgresql-sales
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-sales
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgresql-sales
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: sales
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: postgres:17-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
            failureThreshold: 10
            timeoutSeconds: 20
          name: postgresql-sales
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "268435456"
            requests:
              cpu: 333m
              memory: "134217728"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-sales-data
      restartPolicy: Always
      volumes:
        - name: postgres-sales-data
          persistentVolumeClaim:
            claimName: postgres-sales-data
