apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgresql-warehouse
  name: postgresql-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-warehouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgresql-warehouse
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: warehouses
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: admin
          image: postgres:17-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
            failureThreshold: 10
            timeoutSeconds: 20
          name: postgresql-warehouse
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-warehouse-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      restartPolicy: Always
      volumes:
        - name: postgres-warehouse-data
          persistentVolumeClaim:
            claimName: postgres-warehouse-data
