apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-slave1
  name: redis-slave1
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6379
  selector:
    io.kompose.service: redis-slave1
