apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-sentinel2
  name: redis-sentinel2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-sentinel2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis-sentinel2
    spec:
      containers:
        - env:
            - name: REDIS_MASTER_PASSWORD
              value: password
            - name: SENTINEL_DOWN_AFTER
              value: "5000"
            - name: SENTINEL_FAILOVER
              value: "15000"
            - name: SENTINEL_QUORUM
              value: "2"
          image: redis-sentinel2
          name: redis-sentinel2
          ports:
            - containerPort: 26379
              protocol: TCP
          resources:
            limits:
              cpu: 333m
              memory: "268435456"
            requests:
              cpu: 167m
              memory: "134217728"
          volumeMounts:
            - mountPath: /data
              name: redis-sentinel2-data
      restartPolicy: Always
      volumes:
        - name: redis-sentinel2-data
          persistentVolumeClaim:
            claimName: redis-sentinel2-data
