apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-sentinel2
  name: redis-sentinel2
spec:
  ports:
    - name: "26380"
      port: 26380
      targetPort: 26379
  selector:
    io.kompose.service: redis-sentinel2
