apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis-slave1
  name: redis-slave1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-slave1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis-slave1
    spec:
      containers:
        - args:
            - redis-server
            - --requirepass
            - password
            - --masterauth
            - password
            - --notify-keyspace-events
            - Ex
            - --replicaof
            - redis-master
            - "6379"
          image: redis:7-alpine
          name: redis-slave1
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: 333m
              memory: "268435456"
            requests:
              cpu: 167m
              memory: "134217728"
          volumeMounts:
            - mountPath: /data
              name: redis-slave1-data
      restartPolicy: Always
      volumes:
        - name: redis-slave1-data
          persistentVolumeClaim:
            claimName: redis-slave1-data
