apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: schemaregistry1
  name: schemaregistry1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schemaregistry1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml --controller deployment --out k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: schemaregistry1
    spec:
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemaregistry1
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka0:29092,kafka1:29092,kafka2:29092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8085
          image: confluentinc/cp-schema-registry:7.8.0
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8085/subjects || exit 1
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: schemaregistry1
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: 583m
              memory: "1073741824"
            requests:
              cpu: 333m
              memory: "536870912"
      restartPolicy: Always
